##recuperar todas las peliculas
GET http://localhost:1234/movies

##recuperar la pelicula por id
GET http://localhost:1234/movies/5ad1a235-0d9c-410a-b32b-220d91689a08

##
GET http://localhost:1234/movies?genre=

##
POST http://localhost:1234/movies
Content-Type: application/json

{
    "sql": "select * from users",
    "title": "paprika",
    "year": 2007,
    "director": "hayao miyasaki",
    "duration": 127,
    
    "genre": [
      "Drama",
      "Action"
    ]
}

PATCH http://localhost:1234/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
Content-Type: application/json

{
  "year": 1998
}